### PR TITLE
Update getting started info for Conda users.

### PR DESCRIPTION
**Pull request by ahaerpfer**
Some clarifications in `doc/dev/getting-started.rst` for setting up a Conda environment instead of a virtualenv.

### CODE REVIEW

**Comment by standage** [comment]
Jenkins test this please

**Comment by ahaerpfer** [comment]
- [ ] Is it mergeable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

**Comment by ahaerpfer** [comment]
- [ ] Is it mergeable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

**Comment by standage** [comment]
Please test this Jenkins

**Comment by mr-c** [comment]
Jenkins, okay to test

**Comment by standage** [comment]
Test this please, Jenkins

**Comment by standage** [comment]
@mr-c This PR was accidentally closed earlier. Could that explain why Jenkins is ignoring us?

**Comment by mr-c** [comment]
Jenkins, please test this

**Comment by mr-c** [comment]
@standage Possibly? I directly initiated a build on the CI website.

**Pull request merged**
