### PR TITLE
Remove khmer.load_pe module

### PR DESCRIPTION
**Pull request by kdmurray91**
Addresses #784 

Just did a `git rm khmer/load_pe.py`.

### CODE REVIEW

**Comment by kdmurray91** [comment]
retest this please

**Comment by mr-c** [comment]
Jenkins, test this please

**Comment by mr-c** [comment]
Great! 

- [ ] Is it mergeable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

**Comment by mr-c** [comment]
Thanks @kdmurray91

**Pull request merged**
