### PR TITLE
Fix/793

### PR DESCRIPTION
**Pull request by SchwarzEM**
Added URLs and brief descriptions for khmer-relevant documentation in doc/introduction.txt, pointing to http://khmer-protocols.readthedocs.org and http://khmer-recipes.readthedocs.org, with brief descriptions of their content; hopefully, fixes issue #793.

### CODE REVIEW

**Comment by SchwarzEM** [comment]
- [X] Is it mergeable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [X] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

**Comment by SchwarzEM** [comment]
(I only added the ChangeLog entry after the initial push, since I was following documentation rather naively; in the future I should know better!)

**Comment by ctb** [comment]
Thanks, looks good. One thing to avoid in the future is reformatting lines unnecessarily - most of your
changes were to spacing/end of line in otherwise untouched text, which present as differences on github. I'm going to run the tests pro-forma but since you didn't touch any code I expect them to pass :)

**Comment by ctb** [comment]
ok to test

**Comment by ctb** [comment]
(I also ran a spellchecker. All looks good.)

**Comment by SchwarzEM** [comment]
On Mar 14, 2015, at 8:50 AM, C. Titus Brown <notifications@github.com> wrote:

> Thanks, looks good. One thing to avoid in the future is reformatting lines unnecessarily - most of your
> changes were to spacing/end of line in otherwise untouched text, which present as differences on github.

    Aha.  OK, from now on I'll watch for that...

    git is clearly going to take me more time to work with before it becomes second nature, but at least now I've gotten a *taste* of the Brown lab github workflow.  ;)


--Erich

**Pull request merged**
