### PR TITLE
Fix Issue 669: Check that output and info files in load-into-counting.py are writable before loading input

### PR DESCRIPTION
**Pull request by pgarland**
- [x] Is it mergable?
- [x] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage.
- [x] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual fixing as needed.
- [x] Is it documented in the ChangeLog?
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
@pgarland is this ready to review?

**Comment by ctb** [comment]
(It should also be updated from master)

**Comment by bocajnotnef** [comment]
@pgarland Status on this?

**Comment by mr-c** [comment]
@bocajnotnef Go for it.

**Comment by bocajnotnef** [comment]
@mr-c Alrighty. WIlco.

**Pull request merged**
