### PR TITLE
split test for extract_long_sequences into test for fa and for fq

### PR DESCRIPTION
**Pull request by jessicamizzi**
splitting test_extract_long_sequences into 2 tests specific to fasta and fastq formats as described in issue #825

### CODE REVIEW

**Comment by jessicamizzi** [comment]
- [ ] Is it mergeable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

**Comment by jessicamizzi** [comment]
can I get two pairs of eyes to look over this? @b-wyss @bocajnotnef @brtaylor92 @wrightmhw

**Comment by bocajnotnef** [comment]
LGTM, minus the merge conflict; do a `git pull [whichever remote gedlab is] master` and watch for the conflict.

**Comment by ctb** [comment]
Uhh, should this have been merged, @mr-c?

**Comment by bocajnotnef** [comment]
Technically no, but the end result of the CR was that it should be merged.
(I attempted to revert, then attempted to revert my revert and I'm not
totally certain where that landed. @mr-c said he would sort it out the next
time he was on the ground.)

**Comment by ctb** [comment]
OK. I see fragmented versions of that conversation on slack, too; in the future, let's please document in the issue/PR itself :)

**Pull request merged**
