### PR TITLE
doc/LICENSE.txt => LICENSE

### PR DESCRIPTION
**Pull request by scottsievert**
From issue #482

I changed "docs/LICENSE.txt" to "LICENSE" in the header for files in tests/, scripts/, sandbox/, lib/

### CODE REVIEW

**Comment by mr-c** [comment]
Jenkins, okay to test

**Comment by mr-c** [comment]
Jenkins, ok to test

**Comment by scottsievert** [comment]
- [ ] Is it mergeable?
- [X] Did it pass the tests?
- [X] If it introduces new functionality in scripts/ is it tested? *(no)*
  Check for code coverage with `make clean diff-cover`
- [X] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [X] Did it change the command-line interface? *(no)* Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [X] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [X] Was a spellchecker run on the source code and documentation after
  changes were made?

**Comment by scottsievert** [comment]
@mr-c ready for review!

**Comment by mr-c** [comment]
Hey @scottsievert, an extra file krept in: `sandbox/tmpMZWLFfkhmer/V1.UC-14.trimmed.fa.gz.pass2`

**Comment by mr-c** [comment]
Otherwise this looks good to me.

**Comment by ctb** [comment]
ping @scottsievert

**Comment by scottsievert** [comment]
This PR does not feel important and I'm busy with school.

**Comment by ctb** [comment]
On Tue, May 12, 2015 at 08:07:50AM -0700, Scott S. wrote:
> This PR does not feel important and I'm busy with school.

ok, we'll take it over - thanks for letting us know!

**Comment by mr-c** [comment]
I removed the extra files added to sandbox and resolved the merge conflicts.

@scottsievert Congratulations on your first commit to the khmer project! Your name will be included in the release notes for the next version and you'll be listed amongst our other contributors in the next software release paper.

**Pull request closed without merging**
