### PR TITLE
remove unused callback code

### PR DESCRIPTION
**Pull request by mr-c**
Looks like it isn't used (note all the `#if(0)`) and it doesn't work with multiple threads.

Let's discuss.

### CODE REVIEW

**Comment by mr-c** [comment]
ping @ctb @camillescott @luizirber

**Comment by mr-c** [comment]
- [ ] Is it mergeable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

**Comment by ctb** [comment]
LGTM; nice cleanup!

**Comment by mr-c** [comment]
Thanks!

**Pull request merged**
