### PR TITLE
post merge cleanup of #749

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by mr-c** [comment]
https://github.com/ged-lab/khmer/pull/749#discussion_r24444014 still needs addressing

**Comment by ctb** [comment]
*whistles nonchalantly* nothing to see here.  Ready for review.

**Comment by mr-c** [comment]
Testing FTW :-)

- [ ] Is it mergable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

**Comment by ctb** [comment]
hang on a bit, fixing something else.

**Comment by ctb** [comment]
test this please

**Comment by ctb** [comment]
Ready for review.

**Comment by ctb** [comment]
Actually, now I'm confused. You made some changes, I made some changes... who should review? :)

**Comment by mr-c** [comment]
:-) This PR is all you. LGTM; merging

**Comment by ctb** [comment]
Excellent.  (I knew I could slide stuff by you by changing hash to counting and hashbits to presence :)

**Comment by mr-c** [comment]
You know me well!

**Pull request merged**
