### PR TITLE
Add pep257 targets to Makefile in preparation of docstrings cleanup.

### PR DESCRIPTION
**Pull request by ahaerpfer**
- [x] Is it mergeable?
- [x] Did it pass the tests?
- [x] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [x] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ahaerpfer** [comment]
Working towards PEP 257 cleanup (#866).

However:
* The pep257 tool does not (yet) have some of the command line options that pep8 has.  In particular `--exclude` is missing (see https://github.com/GreenSteam/pep257/pull/22).

* There is no explicit *pep257* plugin for *diff-quality*.  Output format looks equivalent to that from pep8 so I'll  use that one in the *diff_pep257_report* target for now.

**Comment by standage** [comment]
Jenkins, ok to test.

**Comment by ahaerpfer** [comment]
Fixed most of the formal complaints of the PEP 257 parser.

TODO:
* Fix cases where the summary line of the docstring is more than a single line.  PEP 257 always requires a one-line summary.
* Add all the missing docstrings for classes and functions … and there are *a lot*.

**Comment by ahaerpfer** [comment]
**Status:**
* New `make pep257` target in the Makefile.
* PEP 257 checks for missing docstrings are currently disabled/ignored.
* Apart from that the docstrings in all .py files are now also PEP 257 clean.

… **however:** Please also cross-check the *meaning* of my edits since I'm not sure if I got the terminology right in all cases.

**TODO:**
* Add all the missing docstrings!

**Comment by ahaerpfer** [comment]
addendum: added the report files for both PEP 8 and PEP 257 to *.gitignore*.

**Comment by mr-c** [comment]
Top notch! @ahaerpfer Congratulations on your first commit to the khmer project! Your name will be included in the release notes for the next version and you'll be listed amongst our other contributors in the next software release paper.

**Pull request merged**
