### PR TITLE
Avoiding running big-memory requests on OS X

### PR DESCRIPTION
**Pull request by ctb**
The new behavior from #771 breaks Mac OS X tests when 'nosetests' is run, because the !linux flag isn't set. Fixed by making default behavior to not run those tests.

### CODE REVIEW

**Comment by ctb** [comment]
- [ ] Is it mergable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage.
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Is it documented in the ChangeLog?
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

**Comment by ctb** [comment]
ready for review / discussion

**Comment by mr-c** [comment]
Fine. Merge away

**Comment by ctb** [comment]
Made mergeable!

**Pull request merged**
