### PR TITLE
Remove unused versions of MurmurHash3; fix #888

### LINKED ISSUE #888: smhasher implicit conversion loses integer precision
From the OS X build logs

```
third-party/smhasher/MurmurHash3.cc:98:27: warning: implicit conversion loses integer precision: 'unsigned long' to 'const int' [-Wshorten-64-to-32]
  const int nblocks = len / 4;
            ~~~~~~~   ~~~~^~~
third-party/smhasher/MurmurHash3.cc:154:27: warning: implicit conversion loses integer precision: 'unsigned long' to 'const int' [-Wshorten-64-to-32]
  const int nblocks = len / 16;
            ~~~~~~~   ~~~~^~~~
third-party/smhasher/MurmurHash3.cc:259:27: warning: implicit conversion loses integer precision: 'unsigned long' to 'const int' [-Wshorten-64-to-32]
  const int nblocks = len / 16;
            ~~~~~~~   ~~~~^~~~
4 warnings generated.
```

### PR DESCRIPTION
**Pull request by luizirber**
We only use MurmurHash3_x64_128, no need to keep x86 and 32-bits versions.

### CODE REVIEW

**Comment by luizirber** [comment]
Jenkins, test this please

**Comment by mr-c** [comment]
Yay for deleting code :-)

**Comment by luizirber** [comment]
- [ ] Is it mergable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage.
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Is it documented in the ChangeLog?
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

**Comment by luizirber** [comment]
test this please, jenkins

**Comment by luizirber** [comment]
ready for review @mr-c

**Comment by mr-c** [comment]
Merci beaucoup

**Pull request merged**
