### PR TITLE
Migrating from #557: "added silly test for empty file warning"

### PR DESCRIPTION
**Pull request by bocajnotnef**
Pull at #557 stagnated; Migrated here to clean up and merge.

- [x] Is it mergeable?
- [x] Did it pass the tests?
- [x] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [x] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

Unsure of how to do the changelog; work belongs to @wltrimbl but I cannot find a contact email for them.

### CODE REVIEW

**Comment by bocajnotnef** [comment]
@wrightmhw @jessicamizzi @b-wyss CR please?

**Comment by bocajnotnef** [comment]
@mr-c Thoughts on Changelog?

**Comment by mr-c** [comment]
@bocajnotnef Make it in the name of @wltrimbl

**Comment by bocajnotnef** [comment]
@mr-c And leave out the email?

**Comment by mr-c** [comment]
I can't find a public email address for him, so yes for now.

**Comment by bocajnotnef** [comment]
@mr-c Updated

**Comment by bocajnotnef** [comment]
@mr-c Mergable!

**Comment by mr-c** [comment]
Thank you @pgarland and @bocajnotnef

**Pull request merged**
