### PR TITLE
Update documentation for force and squash options

### PR DESCRIPTION
**Pull request by davelin1**
Fix Issue #925

### CODE REVIEW

**Comment by mr-c** [comment]
Jenkins, okay to test

**Comment by mr-c** [comment]
Jenkins, ok to test

**Comment by davelin1** [comment]
- [X] Is it mergeable?
- [X] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [X] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [X] Was a spellchecker run on the source code and documentation after
  changes were made?

**Comment by davelin1** [comment]
ready for review!

**Comment by mr-c** [comment]
LGTM, except for the lack of ChangeLog entry.

**Comment by davelin1** [comment]
Added description to ChangeLog

**Comment by mr-c** [comment]
@davelin1 Congratulations on your first commit to the khmer project! Your name will be included in the release notes for the next version and you'll be listed amongst our other contributors in the next software release paper.

**Pull request merged**
